### ISSUE TITLE
Soft lock - Nega Yuki Boot lick

### ISSUE THREAD

**Issue by Ropelopunny** [deviant-dev/ds-issues#111] opened 2021-02-01 03:39 UTC
**Describe the bug**

**To Reproduce**
 - Get two skulls and a cup
 - Get boot worship scene

**Expected behavior**
   - Nega should identify that the player is licking her boot

**Screenshots**
![20210131222143_1](https://user-images.githubusercontent.com/60497088/106412183-15eee280-6415-11eb-922a-c8e49115bfb5.jpg)

**System (please complete the following information):**
 - VR Device: Valve Index
 - Version: 2.0.8

**Additional context**

**Comment by Ropelopunny** [comment] 2021-02-01 06:25
Issue confirmed to occur in desktop mode as well

**Comment by HeadphoneTaco** [comment] 2021-02-01 23:35
Confirmed, initial bootlicking pose recognition is successful; but continuing to lick Nega's boots does not work with head movements. Tested on desktop.

**Comment by deviant-dev** [comment] 2021-06-12 08:32
Looks like this is fixed in the latest.

**Comment by HeadphoneTaco** [comment] 2021-06-24 14:57
Confirmed, appears to be fixed as of Ver 2.1.0

**Comment by HeadphoneTaco** [comment] 2021-11-11 18:35
Closing 'caused fixed, yo

**Closed by HeadphoneTaco** 2021-11-11 18:35 UTC
Labels: Gameplay Bug
